FROM node:16-alpine as build
WORKDIR /app
COPY package*.json ./
RUN yarn install
COPY . ./
RUN yarn build

# production env
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]